# Generated by Django 5.2.6 on 2025-10-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_practitionerprofile_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wellnesstip',
            options={'managed': True},
        ),
    ]
