# Generated by Django 5.2.6 on 2025-10-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_wellnesstip_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practitionerprofile',
            name='clinic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='practitionerprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='practitionerprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medical_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
