# Generated by Django 5.2.6 on 2025-10-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_legacyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('therapy_type', models.CharField(choices=[('Abhyanga', 'Abhyanga'), ('Swedana', 'Swedana'), ('Vamana', 'Vamana'), ('Virechana', 'Virechana'), ('Basti', 'Basti')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canceled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
    ]
